version: '3'

services:
  # Servicio principal: Moodle
  moodle:
    #image: bitnami/moodle:latest       # Imagen ultima version
    image: bitnami/moodle:4.5       # Imagen con Moodle 4.5.x
    container_name: moodle
    ports:
      - "8080:8080"                 # Puerto HTTP
      - "8443:8443"                 # Puerto HTTPS (si se usa SSL)
    environment:
      - MOODLE_USERNAME=admin       # Usuario administrador inicial
      - MOODLE_PASSWORD=moodle123   # Contraseña admin
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=moodlepass
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb

  # Servicio de base de datos
  mariadb:
    image: bitnami/mariadb:10.6
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=rootpass
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=moodlepass
    volumes:
      - mariadb_data:/bitnami/mariadb

# Volúmenes persistentes
volumes:
  moodle_data:
  moodledata_data:
  mariadb_data:
